version: 2.1

orbs:
  aws_assume_role_test: lbh-test/aws_assume_role_test@dev:0.1

commands:
  test_aws_resources:
    description: tests whether the assumed role works
    steps:
       - run: |
              aws ecs describe-clusters                   

jobs:
  testing_assume_role:    
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - aws_assume_role_test/assume_role:
          account: $AWS_ACCOUNT
          profile_name: circlecitest
          role: 'LBH_Circle_CI_Deployment_Role'
      - test_aws_resources
workflows:
  main:
    jobs:
      - testing_assume_role